FROM golang:1.17-alpine

RUN  go env -w GOPROXY=https://goproxy.cn,direct && \
     go install github.com/dubbogo/dubbogo-cli@latest




#RUN dubbogo-cli install all
#
#RUN go get -u github.com/golang/protobuf/protoc-gen-go
#
#RUN  apk add --no-cache make protobuf-dev=3.18.1-r1